[Service]
Environment=__EGL_VENDOR_LIBRARY_FILENAMES=/usr/local/ans/share/glvnd/egl_vendor.d/50_mesa.json
Environment=__GLX_VENDOR_LIBRARY_NAME=mesa
Environment=LIBGL_DRIVERS_PATH=/usr/local/ans/lib/dri:/usr/lib/aarch64-linux-gnu/dri
Environment=GBM_BACKENDS_PATH=/usr/local/ans/lib/gbm
